const fs = require('fs');
const path = require('path');

const projectDir = __dirname;
const seedPath = path.join(projectDir, 'menu_items_seed.json');
const outputPath = path.join(projectDir, 'supabase_schema_and_seed.sql');

const items = JSON.parse(fs.readFileSync(seedPath, 'utf8'));

function sqlString(value) {
    if (value === null || value === undefined) {
        return 'null';
    }
    return `'${String(value).replace(/'/g, "''")}'`;
}

const lines = [
    '-- Riko Website Supabase schema and menu seed',
    '-- Run this in Supabase SQL Editor, then set SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY in Vercel.',
    '',
    'create table if not exists public.menu_items (',
    '  id bigint generated by default as identity primary key,',
    '  name text not null,',
    '  slug text not null unique,',
    '  description text not null,',
    '  price numeric not null,',
    '  category text not null,',
    '  image_url text not null,',
    "  status text not null default 'Published'",
    ');',
    '',
    'create table if not exists public.reservations (',
    '  id bigint generated by default as identity primary key,',
    '  name text not null,',
    '  phone text not null,',
    '  guests integer not null,',
    '  date text not null,',
    '  time text not null,',
    '  special_request text,',
    "  status text not null default 'New',",
    '  is_read integer not null default 0,',
    '  created_at text not null',
    ');',
    '',
    'create table if not exists public.reservation_logs (',
    '  id bigint generated by default as identity primary key,',
    '  reservation_id bigint not null references public.reservations(id) on delete cascade,',
    '  action_type text not null,',
    '  prev_status text,',
    '  new_status text not null,',
    '  timestamp text not null',
    ');',
    '',
    'create index if not exists reservations_status_idx on public.reservations(status);',
    'create index if not exists reservations_date_idx on public.reservations(date);',
    'create index if not exists reservation_logs_reservation_id_idx on public.reservation_logs(reservation_id);',
    '',
    '-- Service-role REST access from Flask bypasses RLS. Keep anon/client access disabled unless you add explicit policies.',
    'alter table public.menu_items enable row level security;',
    'alter table public.reservations enable row level security;',
    'alter table public.reservation_logs enable row level security;',
    '',
    'insert into public.menu_items (name, slug, description, price, category, image_url, status) values'
];

items.forEach((item, index) => {
    const slug = item.slug || item.name.toLowerCase().replace(/\s+/g, '-');
    const suffix = index === items.length - 1 ? '' : ',';
    lines.push(
        `  (${sqlString(item.name)}, ${sqlString(slug)}, ${sqlString(item.description)}, ${Number(item.price)}, ${sqlString(item.category)}, ${sqlString(item.image_url)}, ${sqlString(item.status || 'Published')})${suffix}`
    );
});

lines.push(
    'on conflict (slug) do update set',
    '  name = excluded.name,',
    '  description = excluded.description,',
    '  price = excluded.price,',
    '  category = excluded.category,',
    '  image_url = excluded.image_url,',
    '  status = excluded.status;',
    '',
    '-- Verification: should return 78 after the seed import.',
    'select count(*) as menu_item_count from public.menu_items;',
    ''
);

fs.writeFileSync(outputPath, lines.join('\n'), 'utf8');
console.log(`Generated ${path.basename(outputPath)} with ${items.length} menu items.`);
