-- Riko Website Supabase schema and menu seed
-- Run this in Supabase SQL Editor, then set SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY in Vercel.

create table if not exists public.menu_items (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text not null unique,
  description text not null,
  price numeric not null,
  category text not null,
  image_url text not null,
  status text not null default 'Published'
);

create table if not exists public.reservations (
  id bigint generated by default as identity primary key,
  name text not null,
  phone text not null,
  guests integer not null,
  date text not null,
  time text not null,
  special_request text,
  status text not null default 'New',
  is_read integer not null default 0,
  created_at text not null
);

create table if not exists public.reservation_logs (
  id bigint generated by default as identity primary key,
  reservation_id bigint not null references public.reservations(id) on delete cascade,
  action_type text not null,
  prev_status text,
  new_status text not null,
  timestamp text not null
);

create index if not exists reservations_status_idx on public.reservations(status);
create index if not exists reservations_date_idx on public.reservations(date);
create index if not exists reservation_logs_reservation_id_idx on public.reservation_logs(reservation_id);

-- Service-role REST access from Flask bypasses RLS. Keep anon/client access disabled unless you add explicit policies.
alter table public.menu_items enable row level security;
alter table public.reservations enable row level security;
alter table public.reservation_logs enable row level security;

insert into public.menu_items (name, slug, description, price, category, image_url, status) values
  ('Bomba de Choclo', 'bomba-de-choclo', 'A delicate custard of sweet Peruvian corn with aged cheese & crisp shell', 289, 'For One', 'assets/bomba_de_choclo.png', 'Published'),
  ('Papa Cremosas', 'papa-cremosas', 'Crispy golden potato crowned with tangy sour cream and beetroot caviar pearls', 289, 'For One', 'assets/papa_cremosas.png', 'Published'),
  ('Elote Picante', 'elote-picante', 'Smoky grilled corn glazed with spiced garlic butter', 329, 'For One', 'assets/elote_picante.png', 'Published'),
  ('Coliflor Crujiente', 'coliflor-crujiente', 'Golden Cauliflower florets with chermoula and smoky romesco sauce', 389, 'For One', 'assets/coliflor_crujiente.png', 'Published'),
  ('Patatas Bravas Clásicas', 'patatas-bravas-cl-sicas', 'Crispy potatoes with smoked romesco and garlic aioli', 389, 'For One', 'assets/patatas_bravas_clasicas.png', 'Published'),
  ('Papas Umami', 'papas-umami', 'Crispy golden fries tossed with parmesan, seaweed, truffle oil & spring onions', 429, 'For One', 'assets/papas_umami.png', 'Published'),
  ('Croquetas de Queso Fresco', 'croquetas-de-queso-fresco', 'Golden-fried bites of soft cottage cheese blended with spices', 289, 'For One', 'assets/croquetas_de_queso_fresco.png', 'Published'),
  ('Bombas Andinas', 'bombas-andinas', 'Golden empanadas packed with earthy mushrooms and creamy Peruvian cheese', 589, 'For One', 'assets/bombas_andinas.png', 'Published'),
  ('Verde Bombas', 'verde-bombas', 'Golden empanadas filled with tender spinach and creamy Peruvian cheese', 329, 'For One', 'assets/verde_bombas.png', 'Published'),
  ('Queso Bombas', 'queso-bombas', 'Crispy empanadas filled with creamy cheese and tender chicken', 529, 'For One', 'assets/queso_bombas.png', 'Published'),
  ('Empanada Criolla', 'empanada-criolla', 'Golden flaky pastry filled with cinnamon-spiced minced meat', 589, 'For One', 'assets/empanada_criolla.png', 'Published'),
  ('Sopa de Garbanso', 'sopa-de-garbanso', 'Lentil Soup', 329, 'For One', 'assets/sopa_de_garbanso.png', 'Published'),
  ('Ensalada Mercado Verde', 'ensalada-mercado-verde', 'Seasonal lettuces layered with avocado, radish, carrot, and beetroot, gently dressed in lime vinaigrette and fresh herbs', 489, 'Salads', 'assets/ensalada_mercado.png', 'Published'),
  ('Sol de Maiz', 'sol-de-maiz', 'Charred corn with toasted kernels, onions and red chili', 389, 'Salads', 'assets/sol_de_maiz.png', 'Published'),
  ('Pomelo Fresco', 'pomelo-fresco', 'Refreshing salad of fresh pomelo wedges, mixed greens, avocado, and toasted pumpkin seeds, dressed in light lime-honey vinaigrette', 389, 'Salads', 'assets/ensalada_camaron_pomelo.png', 'Published'),
  ('Ensalad de Camarón y Pomelo', 'ensalad-de-camar-n-y-pomelo', 'Mixed lettuces with pomelo, roasted coconut, blueberry, and shrimp in a soy-fish sauce vinaigrette', 589, 'Salads', 'assets/ensalada_camaron_pomelo.png', 'Published'),
  ('Pepino Picante Crunch', 'pepino-picante-crunch', 'Cucumber ribbons with red chili, lime zest and toasted sesame', 295, 'Salads', 'assets/pepino_picante_crunch.png', 'Published'),
  ('Ceviche de Sandia', 'ceviche-de-sandia', 'Watermelon cured in lime with native chili, coriander stem, and sea salt', 549, 'Cold Dishes', 'assets/ceviche_de_sandia.png', 'Published'),
  ('Ceviche Estrella', 'ceviche-estrella', 'Lime-cured dragon fruit and muskmelon, finished with pickled onion and caviar pearls', 389, 'Cold Dishes', 'assets/ceviche_estrella.png', 'Published'),
  ('Ceviche Clásico', 'ceviche-cl-sico', 'Fresh seabass cured in lime juice, finished with aji amarillo or leche de tigre, red onion, chilli and herbs', 589, 'Cold Dishes', 'assets/ceviche_clasico.png', 'Published'),
  ('Ceviche de Mango y Maracuya', 'ceviche-de-mango-y-maracuya', 'Shrimp marinated in mango and passion fruit with herbs and chili', 689, 'Cold Dishes', 'assets/ceviche_de_mango_maracuya.png', 'Published'),
  ('Ceviche Mixto Rojo', 'ceviche-mixto-rojo', 'Octopus, scallops, calamari & shrimp in red aji panca leche de tigre', 589, 'Cold Dishes', 'assets/ceviche_mixto_rojo.png', 'Published'),
  ('Ceviche Fresca', 'ceviche-fresca', 'Layers of creamy Peruvian potato and fresh garden vegetables, gently seasoned with lime aji amarillo', 429, 'Cold Dishes', 'assets/ceviche_fresca.png', 'Published'),
  ('Causa de Pollo y Huevo', 'causa-de-pollo-y-huevo', 'Mashed yellow potato layered with chicken and egg, finished with lime and ají amarillo mayo.', 489, 'Cold Dishes', 'assets/causa_de_pollo_y_huevo.png', 'Published'),
  ('Causa de Atún', 'causa-de-at-n', 'Mashed yellow potato layered with tuna and avocado, finished with lime and ají amarillo mayo', 589, 'Cold Dishes', 'assets/causa_de_atun.png', 'Published'),
  ('Tartare Andino', 'tartare-andino', 'Beetroot and avocado layered and finished with citrus dressing and fresh herbs', 289, 'Cold Dishes', 'assets/tartare_andino.png', 'Published'),
  ('Tamal de Yaca', 'tamal-de-yaca', 'Soft corn masa filled with tender jackfruit and steamed in corn husk', 489, 'Cold Dishes', 'assets/tamal_de_yaca.png', 'Published'),
  ('Tamal de Cordero', 'tamal-de-cordero', 'Soft corn tamale filled with spiced lamb, steamed in a banana leaf', 529, 'Cold Dishes', 'assets/tamal_de_cordero.png', 'Published'),
  ('Tostada Tropical', 'tostada-tropical', 'Crisp toast topped with fresh mango, creamy avocado and spicy marinated tofu', 669, 'Cold Dishes', 'assets/tostada_tropical.png', 'Published'),
  ('Tostada de Atún', 'tostada-de-at-n', 'Toasted bread topped with marinated spicy tuna, creamy mayo and fresh herbs', 729, 'Cold Dishes', 'assets/tostada_de_atun.png', 'Published'),
  ('Calamar Crocante', 'calamar-crocante', 'Fried calamari rings served with aioli dip', 589, 'Hot Dishes', 'assets/calamar_crocante.png', 'Published'),
  ('Brochetas de Pollo', 'brochetas-de-pollo', 'Chicken skewers marinated in Peruvian spices and chargrilled for rich flavour and tenderness', 679, 'Hot Dishes', 'assets/brochetas_de_pollo.png', 'Published'),
  ('Pollo a la Brasa', 'pollo-a-la-brasa', 'Half rotisserie chicken marinated with traditional Peruvian spices and grilled over open flame', 789, 'Hot Dishes', 'assets/pollo_a_la_brasa.png', 'Published'),
  ('Alitas Picantes', 'alitas-picantes', 'Crispy wings tossed in fiery aji glaze', 529, 'Hot Dishes', 'assets/alitas_picantes.png', 'Published'),
  ('Costillas del Fuego', 'costillas-del-fuego', 'Tender lamb ribs with a refined sweet-and-spicy glaze', 1289, 'Hot Dishes', 'assets/costillas_del_fuego.png', 'Published'),
  ('Gambas a la Brasa', 'gambas-a-la-brasa', 'Succulent tiger prawns grilled and dressed with fresh salsa', 989, 'Hot Dishes', 'assets/gambas_a_la_brasa.png', 'Published'),
  ('Costillas Andinas', 'costillas-andinas', 'Charred lamb chops served with vibrant chimichurri and a smoky burnt cauliflower pureé', 1289, 'Hot Dishes', 'assets/costillas.png', 'Published'),
  ('Arroz bomba (Chicken)', 'arroz-bomba-chicken', 'Saffron-infused bomba rice slow-cooked with tender chicken, layered with smoky aji amarillo paste and finished with fresh herbs', 689, 'Main', 'assets/arroz_bomba_chicken.png', 'Published'),
  ('Arroz bomba (Seafood)', 'arroz-bomba-seafood', 'Saffron-infused bomba rice slow-cooked with fresh seabass, layered with smoky aji amarillo paste and finished with fresh herbs', 898, 'Main', 'assets/arroz_bomba_seafood.png', 'Published'),
  ('Arroz bomba (Tofu)', 'arroz-bomba-tofu', 'Saffron-infused bomba rice slow-cooked with tofu, layered with smoky aji amarillo paste and finished with fresh herbs', 689, 'Main', 'assets/arroz_bomba_tofu.png', 'Published'),
  ('Arroz bomba (Veg)', 'arroz-bomba-veg', 'Saffron-infused bomba rice slow-cooked with veggies, layered with smoky aji amarillo paste and finished with fresh herbs', 529, 'Main', 'assets/arroz_bomba_veg.png', 'Published'),
  ('Chaufa Frito (Veg)', 'chaufa-frito-veg', 'Peruvian-style fried rice wok-tossed with soy, garlic, and ginger, finished with smoky chifa flavours and your choice of vegetables', 489, 'Main', 'assets/chaufa_frito_veg.png', 'Published'),
  ('Chaufa Frito (Chicken)', 'chaufa-frito-chicken', 'Peruvian-style fried rice wok-tossed with soy, garlic, and ginger, finished with smoky chifa flavours and chicken', 529, 'Main', 'assets/chaufa_frito_chicken.png', 'Published'),
  ('Chaufa Frito (Shrimp)', 'chaufa-frito-shrimp', 'Peruvian-style fried rice wok-tossed with soy, garlic, and ginger, finished with smoky chifa flavours and shrimp', 629, 'Main', 'assets/chaufa_frito_shrimp.png', 'Published'),
  ('Fideos Brava', 'fideos-brava', 'Wok-tossed noodles with smoky mushroom and aubergine, coated in bold Peruvian-Latina spices', 629, 'Main', 'assets/fideos_brava.png', 'Published'),
  ('Fideos Picantes Secos con Pollo', 'fideos-picantes-secos-con-pollo', 'Stir-fried noodles with minced chicken, chili oil, and fresh herbs.', 689, 'Main', 'assets/fideos_picantes_secos_pollo.png', 'Published'),
  ('Fideos Picantes con Salsa', 'fideos-picantes-con-salsa', 'Saucy stir-fried noodles with vegetables, chili oil, and fresh herbs', 589, 'Main', 'assets/fideos_picantes_salsa.png', 'Published'),
  ('Fideos Picantes con Pollo', 'fideos-picantes-con-pollo', 'Saucy stir-fried noodles with minced chicken, chili oil, and fresh herbs', 749, 'Main', 'assets/fideos_picantes_con_pollo.png', 'Published'),
  ('Mac & Queso Picante', 'mac-queso-picante', 'Creamy mac and cheese with rocato, aji amarillo, smoky cheddar and charred crumbs', 789, 'Main', 'assets/mac_queso_picante.png', 'Published'),
  ('Pasta Verde Vegetariana', 'pasta-verde-vegetariana', 'Fresh pasta of the day, tossed with seasoned greens and fragrant herbs', 489, 'Main', 'assets/pasta_verde_vegetariana.png', 'Published'),
  ('Pasta de Pollo Peruano', 'pasta-de-pollo-peruano', 'Chicken in Peruvian cream sauce with fresh pasta', 589, 'Main', 'assets/pasta_de_pollo_peruano.png', 'Published'),
  ('Pasta del Mar', 'pasta-del-mar', 'Seafood with delicate pasta and Peruvian spices', 789, 'Main', 'assets/pasta_del_mar.png', 'Published'),
  ('Filete de Pescado con Harissa', 'filete-de-pescado-con-harissa', 'Grilled barramundi fillet served with harissa and herbed chermoula', 1489, 'Main', 'assets/filete_de_pescado_con_harissa.png', 'Published'),
  ('Paella Andina', 'paella-andina', 'Bomba rice cooked with saffron and seasonal vegetables, finished with olive oil', 898, 'Main', 'assets/paella_andina.png', 'Published'),
  ('Arroz Marina Peruano', 'arroz-marina-peruano', 'Bomba rice cooked with saffron and seasonal seafood, finished with olive oil', 1389, 'Main', 'assets/arroz_marina_peruano.png', 'Published'),
  ('Lomo Saltado de Cordero', 'lomo-saltado-de-cordero', 'Tender strips of Lamb with onions and tomatoes in a soy-lime sauce, finished with native Peruvian chili, served with crispy fries and steamed rice.', 689, 'Main', 'assets/lomo_saltado_de_cordero.png', 'Published'),
  ('Lomo Saltado', 'lomo-saltado', 'Tender strips of wok-tossed vegetables with onions and tomatoes in a soy-lime sauce, finished with native Peruvian chili, served with crispy fries and steamed rice.', 529, 'Main', 'assets/lomo_saltado_veg.png', 'Published'),
  ('Lomo Saltado (Buff)', 'lomo-saltado-buff', 'Tender strips of Buff with onions and tomatoes in a soy-lime sauce, finished with native Peruvian chili, served with crispy fries and steamed rice.', 629, 'Main', 'assets/lomo_saltado_buff.png', 'Published'),
  ('Andean Ember (Veg)', 'andean-ember-veg', 'Choice of vegetables flame-grilled with smoky chipotle glaze, served with sautéed vegetables, jasmine rice, and chipotle gravy', 629, 'Main', 'assets/andean_ember_veg.png', 'Published'),
  ('Andean Ember (Seafood)', 'andean-ember-seafood', 'Salmon flame-grilled with smoky chipotle glaze, served with sautéed vegetables, jasmine rice, and chipotle gravy', 989, 'Main', 'assets/andean_ember_seafood.png', 'Published'),
  ('Andean Ember (Chicken)', 'andean-ember-chicken', 'Chicken flame-grilled with smoky chipotle glaze, served with sautéed vegetables, jasmine rice, and chipotle gravy', 789, 'Main', 'assets/andean_ember_chicken.png', 'Published'),
  ('Bocado Inca', 'bocado-inca', 'A crispy potato patty layered with fresh Andean flavors', 529, 'Main', 'assets/bocado_inca.png', 'Published'),
  ('Hamburguesa Andina (Lamb)', 'hamburguesa-andina-lamb', 'Juicy Burger with andean-inspired topping', 629, 'Main', 'assets/hamburguesa_andina_lamb.png', 'Published'),
  ('Hamburguesa Andina (Buff)', 'hamburguesa-andina-buff', 'Juicy Burger with andean-inspired topping', 589, 'Main', 'assets/hamburguesa_andina_buff.png', 'Published'),
  ('Bistec en Salsa Jus', 'bistec-en-salsa-jus', 'Tender buffalo steak finished with a rich jus reduction, served with fermented potato fries.', 989, 'Main', 'assets/bistec_en_salsa_jus.png', 'Published'),
  ('Cachapa con Miel', 'cachapa-con-miel', 'Traditional corn pancake drizzled with honey', 489, 'Desserts', 'assets/cachapa_con_miel.png', 'Published'),
  ('Dulce Oscuro', 'dulce-oscuro', 'Decadent chocolate cake layered with dulce de leche, biscuit crumbs, caramelised makhana, rice crisps, and finished with mini meringues swirls', 729, 'Desserts', 'assets/dulce_oscuro.png', 'Published'),
  ('Pina Fuego', 'pina-fuego', 'Peruvian-style crème brûlée layered with fresh saffron ice cream and pineapple, topped with coconut and pineapple custard, finished with caramelized sugar', 829, 'Desserts', 'assets/pina_fuego.png', 'Published'),
  ('Chicha Morada', 'chicha-morada', 'Sweet beverage brewed from purple corn with spices', 689, 'Beverages', 'assets/chicha_morada.png', 'Published'),
  ('Brisa de Durazno Andino', 'brisa-de-durazno-andino', 'Crushed ice with green tea, pickled ginger, lime juice and peach syrup', 689, 'Beverages', 'assets/brisa_de_durazno_andino.png', 'Published'),
  ('Bosque Rubi', 'bosque-rubi', 'Hazelnut syrup with lime juice and cranberry juice', 689, 'Beverages', 'assets/bosque_rubi.png', 'Published'),
  ('Atardecer de la Selva', 'atardecer-de-la-selva', 'Lychee Juice, passion fruit syrup, lime juice and cola', 589, 'Beverages', 'assets/atardecer_de_la_selva.png', 'Published'),
  ('Agua Fresco', 'agua-fresco', 'Light crisp agua fresco made with fresh coconut water and cucumber', 589, 'Beverages', 'assets/agua_fresco.png', 'Published'),
  ('Sandía Picante', 'sand-a-picante', 'Refreshing watermelon juice with ginger and a touch of chili heat', 589, 'Beverages', 'assets/sandia_picante.png', 'Published'),
  ('Granada y Kión', 'granada-y-ki-n', 'Sparkling pomegranate ginger soda with a crisp finish', 629, 'Beverages', 'assets/granada_y_kion.png', 'Published'),
  ('Limonada Cremosa', 'limonada-cremosa', 'Smooth, frothy lemonade blended with milk and vanilla', 589, 'Beverages', 'assets/limonada_cremosa.png', 'Published'),
  ('Poncho de Mango', 'poncho-de-mango', 'Ripe mango purée with lime and chili for a spicy-sweet punch', 629, 'Beverages', 'assets/poncho_de_mango.png', 'Published'),
  ('Kombucha Artesanal', 'kombucha-artesanal', 'Locally fermented probiotic tea infused with natural fruits and botanicals', 489, 'Beverages', 'assets/bosque_rubi.png', 'Published')
on conflict (slug) do update set
  name = excluded.name,
  description = excluded.description,
  price = excluded.price,
  category = excluded.category,
  image_url = excluded.image_url,
  status = excluded.status;

-- Verification: should return 78 after the seed import.
select count(*) as menu_item_count from public.menu_items;
